# Generated by Django 4.2.5 on 2023-09-12 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0002_stocktransaction_average_buy_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransaction",
            name="split_ratio",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Split ratio of the stock",
                max_length=10,
                null=True,
                validators=[django.core.validators.RegexValidator("1:[0-9]+")],
            ),
        ),
    ]
